#!/bin/sh
export CLASSPATH=/usr/local/share/OpenHRP-3.1/java/openhrpstubskel.jar:$CLASSPATH
jython -DNS_OPT="-ORBInitRef NameService=corbaloc:iiop:localhost:2809/NameService" -Dpython.path=/usr/local/share/OpenHRP-3.1/sample/script $@
