// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __ClockGenerator_hh__
#define __ClockGenerator_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif



#ifndef __SDOPackage_hh_EXTERNAL_GUARD__
#define __SDOPackage_hh_EXTERNAL_GUARD__
#include "SDOPackage.hh"
#endif
#ifndef __RTC_hh_EXTERNAL_GUARD__
#define __RTC_hh_EXTERNAL_GUARD__
#include "RTC.hh"
#endif
#ifndef __OpenRTM_hh_EXTERNAL_GUARD__
#define __OpenRTM_hh_EXTERNAL_GUARD__
#include "OpenRTM.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE OpenHRP

_CORBA_MODULE_BEG

#ifndef __OpenHRP_mClockGenerator__
#define __OpenHRP_mClockGenerator__

  class ClockGenerator;
  class _objref_ClockGenerator;
  class _impl_ClockGenerator;
  
  typedef _objref_ClockGenerator* ClockGenerator_ptr;
  typedef ClockGenerator_ptr ClockGeneratorRef;

  class ClockGenerator_Helper {
  public:
    typedef ClockGenerator_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ClockGenerator, ClockGenerator_Helper> ClockGenerator_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ClockGenerator,ClockGenerator_Helper > ClockGenerator_out;

#endif

  // interface ClockGenerator
  class ClockGenerator {
  public:
    // Declarations for this interface type.
    typedef ClockGenerator_ptr _ptr_type;
    typedef ClockGenerator_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ClockGenerator :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    void subscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec, ::CORBA::Double period);
    void unsubscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec);

    inline _objref_ClockGenerator()  { _PR_setobj(0); }  // nil
    _objref_ClockGenerator(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ClockGenerator();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ClockGenerator(const _objref_ClockGenerator&);
    _objref_ClockGenerator& operator = (const _objref_ClockGenerator&);
    // not implemented

    friend class ClockGenerator;
  };

  class _pof_ClockGenerator : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ClockGenerator() : _OMNI_NS(proxyObjectFactory)(ClockGenerator::_PD_repoId) {}
    virtual ~_pof_ClockGenerator();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ClockGenerator :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ClockGenerator();

    virtual void subscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec, ::CORBA::Double period) = 0;
    virtual void unsubscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_OpenHRP
_CORBA_MODULE_BEG

  class ClockGenerator :
    public virtual OpenHRP::_impl_ClockGenerator,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ClockGenerator();

    inline ::OpenHRP::ClockGenerator_ptr _this() {
      return (::OpenHRP::ClockGenerator_ptr) _do_this(::OpenHRP::ClockGenerator::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_OpenHRP
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
OpenHRP::ClockGenerator::_marshalObjRef(::OpenHRP::ClockGenerator_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_ClockGenerator
#endif

#endif  // __ClockGenerator_hh__

