// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "ClockGenerator.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



OpenHRP::ClockGenerator_ptr OpenHRP::ClockGenerator_Helper::_nil() {
  return ::OpenHRP::ClockGenerator::_nil();
}

::CORBA::Boolean OpenHRP::ClockGenerator_Helper::is_nil(::OpenHRP::ClockGenerator_ptr p) {
  return ::CORBA::is_nil(p);

}

void OpenHRP::ClockGenerator_Helper::release(::OpenHRP::ClockGenerator_ptr p) {
  ::CORBA::release(p);
}

void OpenHRP::ClockGenerator_Helper::marshalObjRef(::OpenHRP::ClockGenerator_ptr obj, cdrStream& s) {
  ::OpenHRP::ClockGenerator::_marshalObjRef(obj, s);
}

OpenHRP::ClockGenerator_ptr OpenHRP::ClockGenerator_Helper::unmarshalObjRef(cdrStream& s) {
  return ::OpenHRP::ClockGenerator::_unmarshalObjRef(s);
}

void OpenHRP::ClockGenerator_Helper::duplicate(::OpenHRP::ClockGenerator_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

OpenHRP::ClockGenerator_ptr
OpenHRP::ClockGenerator::_duplicate(::OpenHRP::ClockGenerator_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

OpenHRP::ClockGenerator_ptr
OpenHRP::ClockGenerator::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


OpenHRP::ClockGenerator_ptr
OpenHRP::ClockGenerator::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

OpenHRP::ClockGenerator_ptr
OpenHRP::ClockGenerator::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ClockGenerator _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ClockGenerator* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_ClockGenerator;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* OpenHRP::ClockGenerator::_PD_repoId = "IDL:OpenHRP/ClockGenerator:1.0";


OpenHRP::_objref_ClockGenerator::~_objref_ClockGenerator() {
  
}


OpenHRP::_objref_ClockGenerator::_objref_ClockGenerator(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::OpenHRP::ClockGenerator::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
OpenHRP::_objref_ClockGenerator::_ptrToObjRef(const char* id)
{
  if( id == ::OpenHRP::ClockGenerator::_PD_repoId )
    return (::OpenHRP::ClockGenerator_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::OpenHRP::ClockGenerator::_PD_repoId) )
    return (::OpenHRP::ClockGenerator_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_cOpenRTM_mExtTrigExecutionContextService_i_cdouble
class _0RL_cd_03a8873904bd00ce_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_03a8873904bd00ce_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  OpenRTM::ExtTrigExecutionContextService_var arg_0_;
  OpenRTM::ExtTrigExecutionContextService_ptr arg_0;
  ::CORBA::Double arg_1;
};

void _0RL_cd_03a8873904bd00ce_00000000::marshalArguments(cdrStream& _n)
{
  OpenRTM::ExtTrigExecutionContextService::_marshalObjRef(arg_0,_n);
  arg_1 >>= _n;

}

void _0RL_cd_03a8873904bd00ce_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = OpenRTM::ExtTrigExecutionContextService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();
  (::CORBA::Double&)arg_1 <<= _n;

}

const char* const _0RL_cd_03a8873904bd00ce_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_03a8873904bd00ce_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_03a8873904bd00ce_00000000* tcd = (_0RL_cd_03a8873904bd00ce_00000000*)cd;
  OpenHRP::_impl_ClockGenerator* impl = (OpenHRP::_impl_ClockGenerator*) svnt->_ptrToInterface(OpenHRP::ClockGenerator::_PD_repoId);
  impl->subscribe(tcd->arg_0, tcd->arg_1);


}

void OpenHRP::_objref_ClockGenerator::subscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec, ::CORBA::Double period)
{
  _0RL_cd_03a8873904bd00ce_00000000 _call_desc(_0RL_lcfn_03a8873904bd00ce_10000000, "subscribe", 10);
  _call_desc.arg_0 = ec;
  _call_desc.arg_1 = period;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  void_i_cOpenRTM_mExtTrigExecutionContextService
class _0RL_cd_03a8873904bd00ce_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_03a8873904bd00ce_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  OpenRTM::ExtTrigExecutionContextService_var arg_0_;
  OpenRTM::ExtTrigExecutionContextService_ptr arg_0;
};

void _0RL_cd_03a8873904bd00ce_20000000::marshalArguments(cdrStream& _n)
{
  OpenRTM::ExtTrigExecutionContextService::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_03a8873904bd00ce_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = OpenRTM::ExtTrigExecutionContextService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_03a8873904bd00ce_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_03a8873904bd00ce_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_03a8873904bd00ce_20000000* tcd = (_0RL_cd_03a8873904bd00ce_20000000*)cd;
  OpenHRP::_impl_ClockGenerator* impl = (OpenHRP::_impl_ClockGenerator*) svnt->_ptrToInterface(OpenHRP::ClockGenerator::_PD_repoId);
  impl->unsubscribe(tcd->arg_0);


}

void OpenHRP::_objref_ClockGenerator::unsubscribe(::OpenRTM::ExtTrigExecutionContextService_ptr ec)
{
  _0RL_cd_03a8873904bd00ce_20000000 _call_desc(_0RL_lcfn_03a8873904bd00ce_30000000, "unsubscribe", 12);
  _call_desc.arg_0 = ec;

  _invoke(_call_desc);



}
OpenHRP::_pof_ClockGenerator::~_pof_ClockGenerator() {}


omniObjRef*
OpenHRP::_pof_ClockGenerator::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::OpenHRP::_objref_ClockGenerator(ior, id);
}


::CORBA::Boolean
OpenHRP::_pof_ClockGenerator::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::OpenHRP::ClockGenerator::_PD_repoId) )
    return 1;
  
  return 0;
}

const OpenHRP::_pof_ClockGenerator _the_pof_OpenHRP_mClockGenerator;

OpenHRP::_impl_ClockGenerator::~_impl_ClockGenerator() {}


::CORBA::Boolean
OpenHRP::_impl_ClockGenerator::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "subscribe") ) {

    _0RL_cd_03a8873904bd00ce_00000000 _call_desc(_0RL_lcfn_03a8873904bd00ce_10000000, "subscribe", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "unsubscribe") ) {

    _0RL_cd_03a8873904bd00ce_20000000 _call_desc(_0RL_lcfn_03a8873904bd00ce_30000000, "unsubscribe", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
OpenHRP::_impl_ClockGenerator::_ptrToInterface(const char* id)
{
  if( id == ::OpenHRP::ClockGenerator::_PD_repoId )
    return (::OpenHRP::_impl_ClockGenerator*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::OpenHRP::ClockGenerator::_PD_repoId) )
    return (::OpenHRP::_impl_ClockGenerator*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
OpenHRP::_impl_ClockGenerator::_mostDerivedRepoId()
{
  return ::OpenHRP::ClockGenerator::_PD_repoId;
}

POA_OpenHRP::ClockGenerator::~ClockGenerator() {}

